=== metavacua/subclass/src/main/resources/dtd/docbook.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Simplified DocBook 5.0 DTD for validation testing -->
<!-- This is a minimal DTD for demonstrating DTD validation layer -->

<!-- Article is the root element -->
<!ELEMENT article (info?, section+)>
<!ATTLIST article 
    xmlns CDATA #FIXED "http://docbook.org/ns/docbook"
    version CDATA #FIXED "5.0"
    xml:id ID #IMPLIED>

<!-- Info element contains metadata -->
<!ELEMENT info (title, author?, pubdate?)>

<!-- Title -->
<!ELEMENT title (#PCDATA)>

<!-- Author with personname -->
<!ELEMENT author (personname)>
<!ELEMENT personname (firstname?, surname?)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

<!-- Pubdate -->
<!ELEMENT pubdate (#PCDATA)>

<!-- Section - fixed grouping for mixed content model -->
<!ELEMENT section (title, (para | itemizedlist)+)>
<!ATTLIST section xml:id ID #IMPLIED>

<!-- Paragraph -->
<!ELEMENT para (#PCDATA | emphasis)*>

<!-- Emphasis -->
<!ELEMENT emphasis (#PCDATA)>

<!-- Itemized list -->
<!ELEMENT itemizedlist (listitem+)>

<!-- List item -->
<!ELEMENT listitem (para+)>

=== metavacua/subclass/src/main/xml/samples/docbook-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V5.0//EN" "../../resources/dtd/docbook.dtd">
<article xmlns="http://docbook.org/ns/docbook" version="5.0" xml:id="sample-article">
    <info>
        <title>Sample DocBook 5.0 Document</title>
        <author>
            <personname>
                <firstname>John</firstname>
                <surname>Doe</surname>
            </personname>
        </author>
        <pubdate>2024-01-15</pubdate>
    </info>
    <section xml:id="introduction">
        <title>Introduction</title>
        <para>
            This is a sample DocBook 5.0 document for testing the multi-layer XML validation pipeline.
            It demonstrates the use of DTD validation for structural integrity.
        </para>
    </section>
    <section xml:id="features">
        <title>Features</title>
        <para>
            The validation pipeline includes multiple layers:
        </para>
        <itemizedlist>
            <listitem>
                <para>DTD validation (this layer)</para>
            </listitem>
            <listitem>
                <para>XSD validation</para>
            </listitem>
            <listitem>
                <para>RelaxNG validation</para>
            </listitem>
            <listitem>
                <para>Schematron validation</para>
            </listitem>
            <listitem>
                <para>NVDL validation</para>
            </listitem>
            <listitem>
                <para>Canonicalization (exc-c14n)</para>
            </listitem>
            <listitem>
                <para>Digital signature verification</para>
            </listitem>
        </itemizedlist>
    </section>
</article>
